import "./globals.css";
import Head from "next/head";
import { AuthProvider } from "../contexts";
import { libre_franklin } from "./fonts";

export const metadata = {
  title: "Data Center | Dashboard",
  description: "Generated by create next app",
  keywords: "data, dashboard, research, service",
};

export default function Layout({ title, description, keywords, children }) {
  return (
    <html lang="en">
      <Head>
        <title>{title}</title>
        <meta name="description" content={description}></meta>
        <meta name="keywords" content={keywords}></meta>
      </Head>
      <body className={`${libre_franklin.className} antialiased`}>
        <AuthProvider>
          <div>{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
