import Layout from "../layout";

export const metadata = {
  title: "Subscribete con Nosotros",
  description: "Generated by create next app",
  keywords: "data, dashboard, research, service",
};

export default function LayoutPageSubscribe({ children }) {
  return (
    <Layout metadata={metadata}>
      <div>{children}</div>
    </Layout>
  );
}
